// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu5xzdlMbGZzE0AcUBJlRQpY4LOzDwHzE',
    appId: '1:205993672932:web:b3e257392e2ba38e022cf1',
    messagingSenderId: '205993672932',
    projectId: 'news-6c647',
    authDomain: 'news-6c647.firebaseapp.com',
    storageBucket: 'news-6c647.appspot.com',
    measurementId: 'G-KNH22Y00H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMFoJbiMpGzalQiCYj7WT-vJSEZ16WcPI',
    appId: '1:205993672932:android:96afad2f0a8170e2022cf1',
    messagingSenderId: '205993672932',
    projectId: 'news-6c647',
    storageBucket: 'news-6c647.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDWoIe1K7fIOuAm9DPUO7MCb81Zn7fxsQ',
    appId: '1:205993672932:ios:d19ccbd3c641da53022cf1',
    messagingSenderId: '205993672932',
    projectId: 'news-6c647',
    storageBucket: 'news-6c647.appspot.com',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDWoIe1K7fIOuAm9DPUO7MCb81Zn7fxsQ',
    appId: '1:205993672932:ios:0e98f426b8e7b1d0022cf1',
    messagingSenderId: '205993672932',
    projectId: 'news-6c647',
    storageBucket: 'news-6c647.appspot.com',
    iosBundleId: 'com.example.news.RunnerTests',
  );
}
